# frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-script-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bash-script-frontend
  template:
    metadata:
      labels:
        app: bash-script-frontend
    spec:
      containers:
      - name: bash-script-frontend
        image: your-docker-username/bash-script-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bash-script-frontend
spec:
  selector:
    app: bash-script-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer